server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lmsdb
    username: lms_user
    password: lms123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: staging
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload-directory: lms-uploads
  folder-temp: ./lms-temp/

logging:
  level:
    com.sinaukoding.librarymanagementsystem_SKPlus_Assesment: INFO
